'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
var SET_OPEN = exports.SET_OPEN = 'SET_OPEN';
var TOGGLE_OPEN = exports.TOGGLE_OPEN = 'TOGGLE_OPEN';
var SET_ITEMS = exports.SET_ITEMS = 'SET_ITEMS';
var SET_FILTER = exports.SET_FILTER = 'SET_FILTER';
var SET_NEXT_HIGHLIGHTED = exports.SET_NEXT_HIGHLIGHTED = 'SET_NEXT_HIGHLIGHTED';
var SET_PREV_HIGHLIGHTED = exports.SET_PREV_HIGHLIGHTED = 'SET_PREV_HIGHLIGHTED';
var SET_HIGHLIGHTED = exports.SET_HIGHLIGHTED = 'SET_HIGHLIGHTED';
var SET_SELECTED = exports.SET_SELECTED = 'SET_SELECTED';
var SET_TABINDEX = exports.SET_TABINDEX = 'SET_TABINDEX';
var SET_INITIAL_RENDER_FALSE = exports.SET_INITIAL_RENDER_FALSE = 'SET_INITIAL_RENDER_FALSE';

exports['default'] = {
    SET_OPEN: SET_OPEN,
    SET_ITEMS: SET_ITEMS,
    SET_FILTER: SET_FILTER,
    TOGGLE_OPEN: TOGGLE_OPEN,
    SET_NEXT_HIGHLIGHTED: SET_NEXT_HIGHLIGHTED,
    SET_PREV_HIGHLIGHTED: SET_PREV_HIGHLIGHTED,
    SET_HIGHLIGHTED: SET_HIGHLIGHTED,
    SET_SELECTED: SET_SELECTED,
    SET_TABINDEX: SET_TABINDEX,
    SET_INITIAL_RENDER_FALSE: SET_INITIAL_RENDER_FALSE
};