export const SET_OPEN = 'SET_OPEN';
export const TOGGLE_OPEN = 'TOGGLE_OPEN';
export const SET_ITEMS = 'SET_ITEMS';
export const SET_FILTER = 'SET_FILTER';
export const SET_NEXT_HIGHLIGHTED = 'SET_NEXT_HIGHLIGHTED';
export const SET_PREV_HIGHLIGHTED = 'SET_PREV_HIGHLIGHTED';
export const SET_HIGHLIGHTED = 'SET_HIGHLIGHTED';
export const SET_SELECTED = 'SET_SELECTED';
export const SET_TABINDEX = 'SET_TABINDEX';
export const SET_INITIAL_RENDER_FALSE = 'SET_INITIAL_RENDER_FALSE';


export default {
    SET_OPEN: SET_OPEN,
    SET_ITEMS: SET_ITEMS,
    SET_FILTER: SET_FILTER,
    TOGGLE_OPEN: TOGGLE_OPEN,
    SET_NEXT_HIGHLIGHTED: SET_NEXT_HIGHLIGHTED,
    SET_PREV_HIGHLIGHTED: SET_PREV_HIGHLIGHTED,
    SET_HIGHLIGHTED: SET_HIGHLIGHTED,
    SET_SELECTED: SET_SELECTED,
    SET_TABINDEX: SET_TABINDEX,
    SET_INITIAL_RENDER_FALSE: SET_INITIAL_RENDER_FALSE
}